# organization name, it's used to get github repo url, also in page title
name: node-modules

# badge style, can be "flat", "flat-square" or ""
# see http://shields.io/ for details
badge_style: flat-square

# meta headers in html
title:       node-modules
description: All about node.js modules like your project 'node_modules' dir
keywords:    nodejs, node.js, node, node-modules, node_modules, badgeboard

# list of projects, this will be sorted by name;
# every package is either string or object
# please keep sort by ascii
projects:
 - ab
 - autod
 - address
 - auto-correct
 - agentkeepalive
 - byte
 - bc-rsa
 - bugfree
 - binpack.js
 - buffer-type
 - buffer-concat
 - back-to-thunk
 - cov
 - cutter
 - cfork
 - charset
 - copy-to
 - cache-dns
 - connect-rt
 - digest-header
 - dotfile-config
 - default-user-agent
 - emoji
 - enable
 - error-formatter
 - forwards
 - filestore
 - fast-path
 - formstream
 - fileloader
 - graceful
 - hot-restart
 - humanize-ms
 - humanize-bytes
 - hessian.js
 - is-type-of
 - issue-link
 - interceptor
 - jscover
 - java.io
 - js-to-java
 - jsonp-body
 - loading
 - mm
 - mdit
 - mredis
 - metaweblog
 - microsecond
 - mini-logger
 - logfilestream
 - nab
 - ndir
 - node-patch
 - node-biginteger
 - node-murmurhash
 - onehost
 - optimized
 - pedding
 - parameter
 - printable
 - phantomtest
 - qn
 - qnfs
 - rid
 - restful-wrap
 - restful-client
 - refresh-config
 - response-patch
 - response-cookie
 - speeds
 - sdk-base
 - sqlstring
 - show-methods
 - safe-redirect
 - treekill
 - thunkify-wrap
 - urllib
 - utility
 - urllib-sync
 - userauth
 - vmto
 - var-style
 - wt
 - weibo
 - webcache
 - webcamera
 - weibo-mid
 - urlencode
 - zookeeper-watcher

# list of maintainers, this won't be sorted
maintainers:
 - name:    fengmk2
   github:  fengmk2   # github account, required: we link to it
   npm:     fengmk2   # npm account, required to determine lead maintainer
   twitter: fengmk2   # twitter account, optional
   gittip:  fengmk2   # gittub badge, optional
   email:   fengmk2@gmail.com

 - name:    Yiyu He
   github:  dead-horse
   npm:     dead_horse
   twitter: deadhorse_busi
   gittip:  dead-horse
   email:   heyiyu.deadhorse@gmail.com

 - name:    fool2fish
   github:  fool2fish
   npm:     fool2fish
   twitter: fool2fish
   gittip:  fool2fish
   email:   fool2fish@gmail.com

 - name:    coolme200
   github:  coolme200
   npm:     coolme200
   twitter: coolme200
   gittip:  coolme200
   email:   2001-wms@163.com

 - name:    Haoliang Gao
   github:  popomore
   npm:     popomore
   twitter: popomore
   gittip:  popomore
   email:   sakura9515@gmail.com

 - name:    JacksonTian Tian
   github:  JacksonTian
   npm:     jacksontian
   twitter: JacksonTian
   gittip:  JacksonTian
   email:   shyvo1987@gmail.com

 - name:    alsotang
   github:  alsotang
   npm:     alsotang
   twitter: alsotang
   gittip:  alsotang
   email:   alsotang@gmail.com

 - name:    fish
   github:  fishbar
   npm:     fishbar
   twitter: fishbar
   gittip:  fishbar
   email:   zhengxinlin@gmail.com

 - name:    haoxin
   github:  coderhaoxin
   npm:     coderhaoxin
   twitter: coderhaoxin
   gittip:  coderhaoxin
   email:   coderhaoxin@outlook.com

# this determines what info will be fetched with `make db`;
# you can comment out stuff to reduce number of http requests
db.json:
  projects:
   - node        # node version, it's the lowest version from .travis.yml
   - description # package description from package.json (from npm registry)
   - maintainer  # maintainer npm account (= _npmUser of last published ver)
  maintainers:
   - packages    # amount of packages this npm user has
